[package]
name = "positive_toolbox"
version = "0.1.0"
edition = "2024"
default-run = "positive_toolbox"
license = "AGPL-3.0-only"
description = "面向使用者的工具"
authors = ["TW0hank0"]
repository = "https://github.com/TW0hank0/positive_toolbox"

[[bin]]
name = "positive_toolbox"
path = "src/main.rs"

[[bin]]
name = "code_indenter"
path = "src/tools/code_indenter.rs"

[[bin]]
name = "system_info"
path = "src/tools/system_info.rs"

[[bin]]
name = "about"
path = "src/about/about_main.rs"

[[bin]]
name = "about_show_full_license"
path = "src/about/about_show_full_license.rs"

#[lib]
#crate-type = ["cdylib", "bin"]

[dependencies]
serde = "1.0.228"
serde_json = "1.0.149"
image = "0.25.9"
log = "0.4.28"
time = { version = "0.3.47", features = ["local-offset", "formatting"] }
time-macros = { version = "0.2.27" }
quick-xml = { version = "0.39.0", features = ["serialize"] }
sysinfo = "0.38.1"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced = { version = "0.14.0", features = [
    "x11",
    "thread-pool",
    "wgpu",
    "linux-theme-detection",
    "wayland",
    "debug",
    "advanced",
] }
positive_tool_rs = { git = "https://github.com/TW0hank0/positive_tool_rs" }
open = "5.3.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
iced = { version = "0.14.0", default-features = false, features = [
    "thread-pool",
    "advanced",
    "webgl",
    "wgpu",
    "web-colors",
    "crisp",
] }
getrandom = { version = "0.3.4", features = ["wasm_js"] }
console_log = { version = "1.0.0", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.108"

[build-dependencies]
cargo_metadata = "0.19"
serde = { version = "1.0", features = ["derive"] }
heck = "0.5"
positive_tool_rs = { git = "https://github.com/TW0hank0/positive_tool_rs" }
