# SPDX-License-Identifier: AGPL-3.0-only
# 著作權所有 (C) 2026 TW0hank0
#
# 本檔案屬於 positive_mahjong 專案的一部分。
# 專案儲存庫：https://github.com/TW0hank0/positive_mahjong
#
# 本程式為自由軟體：您可以根據自由軟體基金會發佈的 GNU Affero 通用公共授權條款
# 第 3 版（僅此版本）重新發佈及/或修改本程式。
#
# 本程式的發佈是希望它能發揮功用，但不提供任何擔保；
# 甚至沒有隱含的適銷性或特定目的適用性擔保。詳見 GNU Affero 通用公共授權條款。
#
# 您應該已經收到一份 GNU Affero 通用公共授權條款副本。
# 如果沒有，請參見 <https://www.gnu.org/licenses/>。

name: 錯誤回報（Bug report）
description: 回報非預期行為
title: "[Bug] "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        填寫此issue前，請確認沒有重复的issue。

  - type: textarea
    attributes:
      label: 目前行為
      description: |
        目前行為
    validations:
      required: true

  - type: textarea
    attributes:
      label: 正常行為
      description: |
        正常行為
    validations:
      required: true

  - type: checkboxes
    id: know
    attributes:
      label: 這個issue是唯一的
      options:
        - label: 我已经搜索問題追踪器并且没有發現相同的 issue。
          required: true
