[package]
name = "eazy_updater"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
iced = { workspace=true}
serde_json = { workspace = true }
log = {workspace = true }
ptb_shared = { workspace = true }

[[bin]]
name = "eazy_updater"
path = "src/eazy_updater.rs"
