[package]
name = "ptb_main"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
iced = { workspace = true }
time = { workspace = true }
time-macros = { workspace = true }
log = { workspace = true }
ptb_shared = { workspace = true }
ptb_tools = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
# --- platform: wasm ---
console_log = { workspace = true }
console_error_panic_hook = { workspace = true }
getrandom = { workspace = true }
wasm-bindgen = { workspace = true }

[[bin]]
name = "positive_toolbox"
path = "src/main.rs"
